### PR TITLE
hide ACF Menu

### PR DESCRIPTION
**Pull request by TweetPressFr**
as ACF_LITE will be deprecated we must now implement menu hiding this way

### CODE REVIEW

**Comment by herewithme** [comment]
@TweetPressFr I'm not a fan of using WP_DEBUG. A custom constant to the agency, ex BEA_HIDE_ACF to place in the wp-config is a more explicit alternative I find.

**Comment by TweetPressFr** [comment]
@herewithme I don't see the point here sorry.

**Comment by TweetPressFr** [comment]
It would add more complexity in fact @herewithme (each wp config) and it's not really open source then.

**Comment by petitphp** [comment]
I'm also not a fan of using `WP_DEBUG`. It's too generic, and some projects might be using it in preprod or prod environnement.
We could keep using `ACF_LITE` ? No changes required for current project, and with our muplugin it would still work even if ACF plugin remove its code.

**Comment by TweetPressFr** [comment]
the fact that you are not "fans" is not a real argument. I don't see why prod or preprod would use WP_DEBUG true, never seen that in fact. My test is for WP_DEBUG true. Cheers.

**Comment by Rahe** [comment]
Hello,

For my part, I think that continuing using `ACF_LITE` is a great compromise because this is making the backcompatiblity full.
Nevertheless for me we cannot use the `WP_DEBUG` constant, this is totally different from "developpement mode", this is normally for displaying the debug or not.
Some sites have `WP_DEBUG` to true but need to have the ACF menu available from admin.

Maybe we can use the `WP_ENV` constant instead ? This is by default on all our projects now and we can use like `ACF_LITE` for backcompat and if the `WP_ENV` is present, use it too.

**Comment by TweetPressFr** [comment]
ok guys but what's the point of a github repository if we only use our own constants ?

**Pull request closed without merging**
